language: php
before_install:
        - travis_retry composer self-update
        - composer install
        - composer require --dev phpunit/phpunit ^8
        - composer require php-coveralls/php-coveralls:~1.0@stable

before_script:
        - mkdir -p tests/logs
script:
        - ./vendor/bin/phpunit tests --include-path classes/ --colors=auto --coverage-clover ./tests/logs/clover.xml --configuration="whitelist.xml"
after_script:
        - sh -c 'if( [ "$TRAVIS_PHP_VERSION" != "hhvm" ] ); then php vendor/bin/coveralls -v; fi;'
